### ISSUE TITLE
Improve start address field in ad creation form

### ISSUE THREAD

**Issue by mupendara** [litomba/www#142]
For the start address field of the ad creation form, currently it is not possible to select a metro station for example or an hospital.
In the api results, add all the types described here: https://developers.google.com/places/supported_types

**Comment by AntonioVdlC** [comment]
Mmmh ... ok, because I have actually added a type filter to only get addresses as discussed in this issue #92 😅 

So, if I understand correctly, now we want to let the users select anything they want without limiting it to being a street address, right? 
It's basically just deleting a those few lines of code, so no big deal! 
https://github.com/litomba/www/blob/dev/client/src/components/Input/AddressInput/AddressInput.js#L27-L29

**Comment by mupendara** [comment]
Let's just remove the country values because obviously they will be unusable, and keep all other locations type.
Finally I feel it very restrictive to enter addresses only, like people would not want to enter their own address at first.

Could you store the location type as well? So we can do some analysis and report on the value.
