### ISSUE TITLE
Problem at picture upload on ad creation page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#217]
## Description

On ad creation page, when a user using an android phone uploaded a picture for his/her parcel, an error had been displayed.
The error seems to be displayed on the next page as well (the itinerary page)
Check here for details: http://insights.hotjar.com/p?site=644709&recording=887751481

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Ok, that's a really tricky one!

Basically that happens if you clic on next before the picture is fully uploaded, and therefore the framework tries to update the picture input but it doesn't exist anymore as the user is now on the next page. Therefore it just prints an error message ...

Async is a b*tch! 😅

**Comment by zuluzaire** [comment]
loooooooool
