### ISSUE TITLE
Profile picture not visible anymore

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#339]
## Description

On the live environment, when I login using facebook or using my gmail account, my profile picture is not displayed.
(Works fine on mvp2 environment)

Check image below
![image](https://user-images.githubusercontent.com/30872324/33094568-8b9f534e-cef8-11e7-9a70-f3c9f531b8d6.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

## Environment

Live environment

### Operating System

Windows desktop

### Browser
Chrome

**Comment by AntonioVdlC** [comment]
Just made a quick test and I can't reproduce.

It might be that your connection was quite slow as I am retrieving the pictures from a S3 bucket in Frankfurt (so maybe some latencies there too?).

It may work on staging because I am using different S3 buckets for prod and preprod (just so we have separate environments).

I may investigate further if the problem persists, so let me know if you experience that again!

**Comment by zuluzaire** [comment]
I did experience it again yesterday on my mobile.
It appears randomly.
I will reopen the ticket and put a low priority.

I will keep an eye on it during my hotjar sessions.

**Comment by zuluzaire** [comment]
@AntonioVdlC still broken on the staging app.

I have logged in with facebook, see the result below:
![image](https://user-images.githubusercontent.com/30872324/62013538-f033ae00-b18b-11e9-8239-8cfe1be515eb.png)
