### ISSUE TITLE
Input tooltip display in small screens overlap

### ISSUE THREAD

**Issue by AntonioVdlC** [litomba/www#45]
On small screens the tooltip goes beyond the limit of the screen, which is definitely not good UX ... Needs to be solved, probably using math! 🔢

**Comment by mupendara** [comment]
Changed the priority to P1 because it kinda break the whole good feeling the user may have about our design.
Instead using maths as you were proposing, maybe you can display the "info bulle" at the top of the help icon instead of displaying it at the right of the icon.
In this case we avoid the overlay.

**Comment by AntonioVdlC** [comment]
Even that is not so straight forward ... I implemented another solution that should do the trick for now.
